/**
 * Mock termék adatok teszteléshez
 * Később az igazi adatbázisra lehet váltani
 */
export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Crystal Nails Compact Base Gel',
    price: 3990,
    oldPrice: null,
    description: 'Professzionális minőségű base gel a Crystal Nails-tól',
    category: 'alapanyagok',
    stock: 10,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '2',
    name: 'Moyra Gel Polish Nude Pink',
    price: 2490,
    oldPrice: 2990,
    description: 'Gyönyörű nudzs rózsaszín gel lakk',
    category: 'lakkok',
    stock: 15,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '3',
    name: 'Perfect Nails Primer',
    price: 1890,
    oldPrice: null,
    description: 'Körmöt előkészítő primer',
    category: 'alapanyagok',
    stock: 20,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '4',
    name: 'Cover Pink Builder Gel',
    price: 4590,
    oldPrice: null,
    description: 'Fedő rózsaszín builder gel',
    category: 'alapanyagok',
    stock: 8,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '5',
    name: 'Top Shine No Wipe',
    price: 2790,
    oldPrice: null,
    description: 'Fényes top coat, nem kell törleni',
    category: 'alapanyagok',
    stock: 12,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '6',
    name: 'Nail Prep folyadék',
    price: 1590,
    oldPrice: null,
    description: 'Körmöt előkészítő folyadék',
    category: 'alapanyagok',
    stock: 0,
    active: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '7',
    name: 'Gél lakk Bordeaux Red',
    price: 2690,
    oldPrice: 2990,
    description: 'Elegáns burgundia vörös szín',
    category: 'lakkok',
    stock: 18,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '8',
    name: 'Matt Top Gel',
    price: 2590,
    oldPrice: null,
    description: 'Matt felület topcoat',
    category: 'alapanyagok',
    stock: 14,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '9',
    name: 'Reszelő 100/180',
    price: 390,
    oldPrice: null,
    description: 'Körmreszelő kétoldalú',
    category: 'eszkozok',
    stock: 50,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '10',
    name: 'Cuticle Oil Cherry',
    price: 1290,
    oldPrice: null,
    description: 'Meggyzuhogással illatos kutikula olaj',
    category: 'alapanyagok',
    stock: 16,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '11',
    name: 'Akril ecset',
    price: 2190,
    oldPrice: null,
    description: 'Akril ecset a szépségápoláshoz',
    category: 'eszkozok',
    stock: 0,
    active: false,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
  {
    id: '12',
    name: 'Díszítő ecset vékony',
    price: 1490,
    oldPrice: null,
    description: 'Vékony díszítő ecset részletekhez',
    category: 'diszitok',
    stock: 22,
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
    images: [],
  },
];
